export const leaveData = [
    {
      id: 1,
      userId: 3,
      teamLead: 2,
      type: "Sick Leave",
      startDate: "2026-02-01",
      endDate: "2026-02-01",
      totalDays: 1,
      reason: "Cold & fever",
      status: "pending",
    },
    {
      id: 2,
      userId: 7,
      teamLead: 4,
      type: "Casual Leave",
      startDate: "2026-02-05",
      endDate: "2026-02-05",
      totalDays: 1,
      reason: "Family work",
      status: "approved",
    },
    {
      id: 3,
      userId: 8,
      teamLead: 5,
      type: "Earned Leave",
      startDate: "2026-03-01",
      endDate: "2026-03-05",
      totalDays: 5,
      reason: "Vacation",
      status: "pending",
    },
    {
      id: 4,
      userId: 9,
      teamLead: 4,
      type: "Casual Leave",
      startDate: "2026-02-10",
      endDate: "2026-02-10",
      totalDays: 1,
      reason: "Personal work",
      status: "rejected",
    },
    {
      id: 5,
      userId: 10,
      teamLead: 6,
      type: "Sick Leave",
      startDate: "2026-01-20",
      endDate: "2026-01-21",
      totalDays: 2,
      reason: "Migraine",
      status: "approved",
    },
    {
      id: 6,
      userId: 11,
      teamLead: 4,
      type: "Casual Leave",
      startDate: "2026-02-12",
      endDate: "2026-02-12",
      totalDays: 1,
      reason: "College exam",
      status: "pending",
    },
  
    // ---------- TEAM LEAD LEAVES ----------
    {
      id: 7,
      userId: 2,
      teamLead: null,
      type: "Casual Leave",
      startDate: "2026-02-15",
      endDate: "2026-02-16",
      totalDays: 2,
      reason: "Personal work",
      status: "pending",
    },
    {
      id: 8,
      userId: 4,
      teamLead: null,
      type: "Sick Leave",
      startDate: "2026-01-18",
      endDate: "2026-01-19",
      totalDays: 2,
      reason: "Viral fever",
      status: "approved",
    },
    {
      id: 9,
      userId: 5,
      teamLead: null,
      type: "Earned Leave",
      startDate: "2026-03-10",
      endDate: "2026-03-14",
      totalDays: 5,
      reason: "Vacation",
      status: "rejected",
    },
  
    // ---------- MORE EMPLOYEE LEAVES ----------
    {
      id: 10,
      userId: 3,
      teamLead: 2,
      type: "Casual Leave",
      startDate: "2026-02-25",
      endDate: "2026-02-25",
      totalDays: 1,
      reason: "Personal errand",
      status: "approved",
    },
    {
      id: 11,
      userId: 7,
      teamLead: 4,
      type: "Sick Leave",
      startDate: "2026-03-03",
      endDate: "2026-03-04",
      totalDays: 2,
      reason: "Flu",
      status: "pending",
    },
    {
      id: 12,
      userId: 8,
      teamLead: 5,
      type: "Casual Leave",
      startDate: "2026-02-18",
      endDate: "2026-02-18",
      totalDays: 1,
      reason: "Bank work",
      status: "approved",
    },
    {
      id: 13,
      userId: 9,
      teamLead: 4,
      type: "Sick Leave",
      startDate: "2026-01-30",
      endDate: "2026-01-31",
      totalDays: 2,
      reason: "Food poisoning",
      status: "approved",
    },
    {
      id: 14,
      userId: 10,
      teamLead: 6,
      type: "Earned Leave",
      startDate: "2026-04-01",
      endDate: "2026-04-07",
      totalDays: 7,
      reason: "Family vacation",
      status: "pending",
    },
    {
      id: 15,
      userId: 11,
      teamLead: 4,
      type: "Casual Leave",
      startDate: "2026-03-08",
      endDate: "2026-03-08",
      totalDays: 1,
      reason: "Personal work",
      status: "rejected",
    },
  
    // ---------- MIXED STATUS ----------
    {
      id: 16,
      userId: 3,
      teamLead: 2,
      type: "Earned Leave",
      startDate: "2026-05-01",
      endDate: "2026-05-05",
      totalDays: 5,
      reason: "Trip",
      status: "approved",
    },
    {
      id: 17,
      userId: 7,
      teamLead: 4,
      type: "Casual Leave",
      startDate: "2026-02-28",
      endDate: "2026-02-28",
      totalDays: 1,
      reason: "House shifting",
      status: "rejected",
    },
    {
      id: 18,
      userId: 8,
      teamLead: 5,
      type: "Sick Leave",
      startDate: "2026-03-18",
      endDate: "2026-03-19",
      totalDays: 2,
      reason: "Back pain",
      status: "pending",
    },
    {
      id: 19,
      userId: 10,
      teamLead: 6,
      type: "Casual Leave",
      startDate: "2026-02-08",
      endDate: "2026-02-08",
      totalDays: 1,
      reason: "Family visit",
      status: "approved",
    },
    {
      id: 20,
      userId: 9,
      teamLead: 4,
      type: "Earned Leave",
      startDate: "2026-06-10",
      endDate: "2026-06-15",
      totalDays: 6,
      reason: "Summer vacation",
      status: "pending",
    }
  ];
  
  export const totalLeave = 15;
  